DELETE http://localhost:8080/book/60391c5b4143f523ee99aebe HTTP/1.1

###

GET http://localhost:8080/books HTTP/1.1


###

POST http://localhost:8080/book HTTP/1.1
content-type: application/json

{
    "bookName": "Jari Sillanpää",
    "bookAuthor": "Jariii",
    "bookImg": "https://d1csarkz8obe9u.cloudfront.net/posterpreviews/action-thriller-book-cover-design-template-3675ae3e3ac7ee095fc793ab61b812cc_screen.jpg?ts=1588152105",
    "bookMark": "10",
    "bookMarkDate": "2021-02-24T08:00:00.000Z",
    "bookPages": "100",
    "readStartDate": "2021-02-24T07:00:00.000Z"
}

####

PUT http://localhost:8080/books/60381d9f8a35a00169dd41bf HTTP/1.1
content-type: application/json

{
    "bookName": "Jari Sillanpää",
    "bookAuthor": "Jariii",
    "bookImg": "https://d1csarkz8obe9u.cloudfront.net/posterpreviews/action-thriller-book-cover-design-template-3675ae3e3ac7ee095fc793ab61b812cc_screen.jpg?ts=1588152105",
    "bookMark": "1",
    "bookMarkDate": "2021",
    "bookPages": "100",
    "readStartDate": "2021"
}