FROM node:15.11

USER node
WORKDIR /app

USER root
RUN ["npm", "install", "-g", "npm@7.6.3"]

USER node

COPY --chown=node:node package.json-dev /app/package.json
#RUN npm install --legacy-peer-deps

# We dont need to copy source codes since we will use docker-compose bind mounts
#COPY . .

CMD ["npm", "start"]