version: "3.9"

services:
  mongo:
    container_name: book-mongo-dev
    image: mongo:4.4-bionic
    volumes:
      - mongo-dev:/data/db
  
  back:
    container_name: book-back-dev
    env_file: .env-dev
    image: book-back-dev:${TAG}
    build: 
      context: ./backend
      dockerfile: Dockerfile-compose
    ports:
      - ${REACT_APP_BACKPORT}:${REACT_APP_BACKPORT}
    depends_on:
      - mongo
    volumes:
      - ./backend/src:/app/src
      - ./backend/public:/app/public
      - ./backend/package.json-compose:/app/package.json
    command: npm run dev

  front:
    container_name: book-front-dev
    env_file: .env-dev
    image: book-front-dev:${TAG}
    build:
      context: ./frontend
      dockerfile: Dockerfile-compose
    ports:
      - ${PORT}:${PORT}
    depends_on: 
      - mongo
      - back
    volumes: 
      - ./frontend:/app
      # - ./frontend/package.json-compose:/app/package.json
    environment:
      - NODE_ENV=development     # Not needed maybe?
      - CHOKIDAR_USEPOLLING=true # Needed for bind mounts on OSX
    command: npm start

volumes:
  mongo-dev:

#docker-compose env variable precedence
# Compose file
# Shell environment variables
# Environment file
# Dockerfile
# Variable is not defined
