# For fast building for docker-compose since we mount host volume to workdir
FROM node:15.11

WORKDIR /app

# add node_modules/.bin to path
#ENV PATH /app/node_modules/.bin:$PATH
COPY package.json-compose /app/package.json

RUN npm install

# Using volume mount with compose but lets make sure it works stand alone
#COPY . .

CMD ["npm", "run", "dev"]